In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv('BTR-QSP-Student-Data.csv')
df.head()

,Name,Gender,Date of Birth,Mob No,Email Id,Fresher/Experience,10th Board,10th Year of Pass out,10th Aggregate,12th Board,...,Payment Verification (Amount),Payment Verification (Payment Date),Attendance Tracking (Subject),Attendance Tracking (Batch Code),Attendance Tracking (Attendance),Attendance Tracking (Trainer),Comment,Comments,Receipt No,Post date
0,Shree harsha V K,NaN,NaN,9742872822,shreeharsha.3042@gmail.com,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-01-2018
1,Hemanth N V,NaN,NaN,9886988075,hemanth_babu_star@yahoo.com,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-01-2018
2,M S Ramasubramanya,male,11-05-1993,7022021422,ramasubramanya123@gmail.com,Fresher,SSLC,2009.0,50.00%,Diploma,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-01-2018
3,Satya prakash sahoo,male,26-06-1991,9090396977,spsahoopro1990@gmail.com,Fresher,SSLC,2006.0,72.00%,PUC/ 12th,...,NaN,NaN,Database,QCDM2,1,Rohan.Singh,NaN,NaN,NaN,01-01-2018
4,Nikhil Chaturvedi,NaN,NaN,9098387116,nikhilchat99@gmail.com,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02-01-2018

In [3]:
df.to_excel('QSP-Student.xlsx')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8105 entries, 0 to 8104
Data columns (total 96 columns):
Name                                                        8105 non-null object
Gender                                                      4122 non-null object
Date of Birth                                               4131 non-null object
Mob No                                                      8100 non-null object
Email Id                                                    8100 non-null object
Fresher/Experience                                          5817 non-null object
10th Board                                                  3802 non-null object
10th Year of Pass out                                       3777 non-null float64
10th Aggregate                                              3770 non-null object
12th Board                                                  3771 non-null object
12th Course Type                                            3491 non-null object
12th/Diploma/ITI Year of Pass out                           3768 non-null float64
12th/Diploma/ITI-Aggregate                                  3765 non-null object
Diploma Course Type                                         410 non-null object
Diploma Stream                                              409 non-null object
Other(Diploma Stream)                                       8 non-null object
Diploma University                                          283 non-null object
Other(Diploma University)                                   262 non-null object
Diploma College                                             408 non-null object
Other(Diploma College)                                      369 non-null object
Degree Course Type                                          3766 non-null object
Degree                                                      4030 non-null object
Other(Degree)                                               31 non-null object
Stream in Degree                                            3988 non-null object
Other(Degree Stream)                                        61 non-null object
Degree Year of Pass out                                     4026 non-null float64
Degree Aggregate                                            3904 non-null object
CGPA                                                        258 non-null float64
Degree University                                           3764 non-null object
Other(Degree University)                                    637 non-null object
Degree University Registration No                           3761 non-null object
Degree College Name                                         3790 non-null object
Other(Degree College)                                       1547 non-null object
College Place                                               3930 non-null object
Did You Fail and then clear the subject in Degree           3762 non-null object
Have any existing backlogs in Degree?                       3763 non-null object
Have you got year gap in Degree?                            3763 non-null object
Have you done your Master's Degree?                         3791 non-null object
Master's Degree Course Type                                 414 non-null object
Master's Degree                                             417 non-null object
Other(Master's degree)                                      4 non-null object
Master's Degree Stream                                      414 non-null object
Other(Master's Stream)                                      83 non-null object
Master Degree Aggregate                                     400 non-null object
CGPA.1                                                      54 non-null float64
Master's Degree Year of Pass out                            411 non-null float64
Master's Degree University                                  398 non-null object
Other(Master's University)                                  141 non-null object
Master's Degree University Registration No                  398 non-null object
Master Degree College Name                                  396 non-null object
Other(Master's College)                                     357 non-null object
College Place.1                                             397 non-null object
Did You Fail and then clear the subject in Master Degree    396 non-null object
Have any existing backlogs in Master's Degree?              396 non-null object
Have you got year gap in Master Degree?                     396 non-null object
Highest Degree                                              789 non-null object
Other(Highest Degree)                                       4 non-null object
Native Place                                                787 non-null object
Ready to Relocate                                           4127 non-null object
Preferred Location                                          4020 non-null object
Other(preferred location)                                   14 non-null object
Certifications                                              22 non-null object
Other(certifications)                                       3 non-null object
Do You Have Passport?                                       4123 non-null object
Do You Have Pan Card?                                       3766 non-null object
Do You Have Aadhar Card?                                    3767 non-null object
Do You Have Past Work Experience?                           786 non-null object
Currently Are You Working                                   362 non-null object
Total Experience                                            361 non-null object
Address-First Line                                          3418 non-null object
Street/Area                                                 3414 non-null object
City                                                        4124 non-null object
State                                                       4124 non-null object
Course(s)                                                   4131 non-null object
Enquired Course(s)                                          7200 non-null object
Branch Enquired                                             8105 non-null object
Session                                                     7200 non-null object
Promise Date                                                1313 non-null object
Timing                                                      7199 non-null object
Mode of Enquiry                                             7199 non-null object
Status                                                      8095 non-null object
Approved date                                               3898 non-null object
Balance Fees                                                3904 non-null float64
Target_fees                                                 3900 non-null float64
Payment comments                                            3095 non-null object
Payment Print/Display                                       3437 non-null object
Payment Verification (Amount)                               2356 non-null object
Payment Verification (Payment Date)                         2355 non-null object
Attendance Tracking (Subject)                               3781 non-null object
Attendance Tracking (Batch Code)                            3785 non-null object
Attendance Tracking (Attendance)                            3812 non-null object
Attendance Tracking (Trainer)                               3812 non-null object
Comment                                                     0 non-null float64
Comments                                                    1168 non-null object
Receipt No                                                  2355 non-null object
Post date                                                   8105 non-null object
dtypes: float64(9), object(87)
memory usage: 5.9+ MB

In [7]:
round(df.isnull().sum()/len(df)*100,2)

Name                                     0.00
Gender                                  49.14
Date of Birth                           49.03
Mob No                                   0.06
Email Id                                 0.06
Fresher/Experience                      28.23
10th Board                              53.09
10th Year of Pass out                   53.40
10th Aggregate                          53.49
12th Board                              53.47
12th Course Type                        56.93
12th/Diploma/ITI Year of Pass out       53.51
12th/Diploma/ITI-Aggregate              53.55
Diploma Course Type                     94.94
Diploma Stream                          94.95
Other(Diploma Stream)                   99.90
Diploma University                      96.51
Other(Diploma University)               96.77
Diploma College                         94.97
Other(Diploma College)                  95.45
Degree Course Type                      53.53
Degree                                  50.28
Other(Degree)                           99.62
Stream in Degree                        50.80
Other(Degree Stream)                    99.25
Degree Year of Pass out                 50.33
Degree Aggregate                        51.83
CGPA                                    96.82
Degree University                       53.56
Other(Degree University)                92.14
                                        ...
Do You Have Past Work Experience?       90.30
Currently Are You Working               95.53
Total Experience                        95.55
Address-First Line                      57.83
Street/Area                             57.88
City                                    49.12
State                                   49.12
Course(s)                               49.03
Enquired Course(s)                      11.17
Branch Enquired                          0.00
Session                                 11.17
Promise Date                            83.80
Timing                                  11.18
Mode of Enquiry                         11.18
Status                                   0.12
Approved date                           51.91
Balance Fees                            51.83
Target_fees                             51.88
Payment comments                        61.81
Payment Print/Display                   57.59
Payment Verification (Amount)           70.93
Payment Verification (Payment Date)     70.94
Attendance Tracking (Subject)           53.35
Attendance Tracking (Batch Code)        53.30
Attendance Tracking (Attendance)        52.97
Attendance Tracking (Trainer)           52.97
Comment                                100.00
Comments                                85.59
Receipt No                              70.94
Post date                                0.00
Length: 96, dtype: float64

In [19]:
df['Degree College Name'].isnull().sum()
df['College Place'].isnull().sum()

4175

In [10]:
df.columns

Index(['Name', 'Gender', 'Date of Birth', 'Mob No', 'Email Id',
       'Fresher/Experience', '10th Board', '10th Year of Pass out',
       '10th Aggregate', '12th Board', '12th Course Type',
       '12th/Diploma/ITI Year of Pass out', '12th/Diploma/ITI-Aggregate',
       'Diploma Course Type', 'Diploma Stream', 'Other(Diploma Stream)',
       'Diploma University', 'Other(Diploma University)', 'Diploma College',
       'Other(Diploma College)', 'Degree Course Type', 'Degree',
       'Other(Degree)', 'Stream in Degree', 'Other(Degree Stream)',
       'Degree Year of Pass out', 'Degree Aggregate', 'CGPA',
       'Degree University', 'Other(Degree University)',
       'Degree University Registration No', 'Degree College Name',
       'Other(Degree College)', 'College Place',
       'Did You Fail and then clear the subject in Degree',
       'Have any existing backlogs in Degree?',
       'Have you got year gap in Degree?',
       'Have you done your Master's Degree?', 'Master's Degree Course Type',
       'Master's Degree', 'Other(Master's degree)', 'Master's Degree Stream',
       'Other(Master's Stream)', 'Master Degree Aggregate', 'CGPA.1',
       'Master's Degree Year of Pass out', 'Master's Degree University',
       'Other(Master's University)',
       'Master's Degree University Registration No',
       'Master Degree College Name', 'Other(Master's College)',
       'College Place.1',
       'Did You Fail and then clear the subject in Master Degree',
       'Have any existing backlogs in Master's Degree?',
       'Have you got year gap in Master Degree?', 'Highest Degree',
       'Other(Highest Degree)', 'Native Place', 'Ready to Relocate',
       'Preferred Location', 'Other(preferred location)', 'Certifications',
       'Other(certifications)', 'Do You Have Passport?',
       'Do You Have Pan Card?', 'Do You Have Aadhar Card?',
       'Do You Have Past Work Experience?', 'Currently Are You Working',
       'Total Experience', 'Address-First Line', 'Street/Area', 'City',
       'State', 'Course(s)', 'Enquired Course(s)', 'Branch Enquired',
       'Session', 'Promise Date', 'Timing', 'Mode of Enquiry', 'Status',
       'Approved date', 'Balance Fees', 'Target_fees', 'Payment comments',
       'Payment Print/Display', 'Payment Verification (Amount)',
       'Payment Verification (Payment Date)', 'Attendance Tracking (Subject)',
       'Attendance Tracking (Batch Code)', 'Attendance Tracking (Attendance)',
       'Attendance Tracking (Trainer)', 'Comment', 'Comments', 'Receipt No',
       'Post date'],
      dtype='object')

In [20]:
df['Status'].fillna('unknoun',inplace=True)
df['Gender'].fillna('unknoun',inplace=True)
df['Fresher/Experience'].fillna('unknoun',inplace=True)
df['10th Aggregate'].fillna(0,inplace=True)
df['12th/Diploma/ITI-Aggregate'].fillna(0,inplace=True)
df['Stream in Degree'].fillna('unknoun',inplace=True)
df['Degree Year of Pass out'].fillna(0,inplace=True)
df['Degree Aggregate'].fillna(0,inplace=True)
df['City'].fillna('unknoun',inplace=True)
df['State'].fillna('unknoun',inplace=True)
df['Course(s)'].fillna('unknoun',inplace=True)
df['Session'].fillna('unknoun',inplace=True)
df['Mode of Enquiry'].fillna('unknoun',inplace=True)
df['Status'].fillna('unknoun',inplace=True)
df['Approved date'].fillna('unknoun',inplace=True)
df['Degree College Name'].fillna('unknown',inplace=True)
df['College Place'].fillna('unknown',inplace=True)

In [28]:
df1=df[['Name', 'Gender','Fresher/Experience','10th Aggregate','12th/Diploma/ITI-Aggregate','Stream in Degree',
    'Degree Year of Pass out','Degree Aggregate','Degree College Name','College Place','State','Course(s)',
   'Session', 'Mode of Enquiry','Status','Approved date']]

In [29]:
df1.head()

,Name,Gender,Fresher/Experience,10th Aggregate,12th/Diploma/ITI-Aggregate,Stream in Degree,Degree Year of Pass out,Degree Aggregate,Degree College Name,College Place,State,Course(s),Session,Mode of Enquiry,Status,Approved date
0,Shree harsha V K,unknoun,unknoun,0,0,unknoun,0.0,0,unknown,unknown,unknoun,unknoun,Morning,Walk-in,Old Enquiry,unknoun
1,Hemanth N V,unknoun,unknoun,0,0,unknoun,0.0,0,unknown,unknown,unknoun,unknoun,Morning,Walk-in,Old Enquiry,unknoun
2,M S Ramasubramanya,male,Fresher,50.00%,76.77%,Civil,2017.0,69.67%,Bangalore Institute of Technology,BANGALORE,Karnataka,Classic Selenium,Evening,QSpiders Website,Converted,30-02-2018
3,Satya prakash sahoo,male,Fresher,72.00%,46.00%,Computer Science(CS),2011.0,56.00%,Other,PURI,Karnataka,Classic Selenium,Morning,Telephonic,Converted,30-01-2018
4,Nikhil Chaturvedi,unknoun,unknoun,0,0,unknoun,0.0,0,unknown,unknown,unknoun,unknoun,"Morning, Evening, Afternoon",QSpiders Website,Old Enquiry,unknoun

In [31]:
df1.shape

(8105, 16)

In [32]:
df1.isnull().sum()

Name                          0
Gender                        0
Fresher/Experience            0
10th Aggregate                0
12th/Diploma/ITI-Aggregate    0
Stream in Degree              0
Degree Year of Pass out       0
Degree Aggregate              0
Degree College Name           0
College Place                 0
State                         0
Course(s)                     0
Session                       0
Mode of Enquiry               0
Status                        0
Approved date                 0
dtype: int64

In [34]:
df1.to_excel('BTR-QSP-Students.xlsx')